% delta_ios = delta_ios(:, end);
 U    = mU(:,    end);

sR = [0.01 0.02 0.04 0.08 0.25 0.4];
R = [sR sR sR sR]';
g = [...
    9.8  * ones(size(sR)) ...
    98   * ones(size(sR)) ...
    980  * ones(size(sR)) ...
    4900 * ones(size(sR)) ...
    ]';
k = [...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    ]';
Ra = [...
    1e6*ones(size(sR)) ...
    1e7*ones(size(sR)) ...
    1e8*ones(size(sR)) ...
    5e8*ones(size(sR)) ...
    ]';
visco = [...
    0.001*ones(size(sR)) ...
    0.001*ones(size(sR)) ...
    0.001*ones(size(sR)) ...
    0.001*ones(size(sR)) ...
    ]';
alpha = [...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    0.0001*ones(size(sR)) ...
    ]';

SimUz = @(Rr, Ttheta) ((Rr+Ttheta)./((Rr+Ttheta/2)))./(((Rr+Ttheta/2)./(Rr+Ttheta))+1);

figure
plot(k.*SimUz(R, delta_ios)./delta_ios.^2./g, U, '-*');

figure
plot(R, SimUz(R, delta_ios), '-*')
hold on
plot(linspace(min(R), max(R), 100), SimUz(linspace(min(R), max(R), 100),0.059))

figure
plot(U, k.*((2*R+2*delta_ios/3)./((R+delta_ios/2).*(delta_ios.^2)))./(((R+delta_ios/2)./(R+delta_ios))+1), '*');

lhs = 0.5*visco.*alpha./(g*0.0016*7); 
var_f = @(A)10000*var((lhs.*((R+delta_ios/3)./(R+delta_ios/2)).*((R+delta_ios*A)./(R+delta_ios/2)))./((delta_ios.^4).*((R+delta_ios/2)./(R+delta_ios)+1)));
ef = @(C)sum(((lhs.*((R+delta_ios/3)./(R+delta_ios/2)).*((R+delta_ios*C(1))./(R+delta_ios/2)))./((delta_ios.^4).*((R+delta_ios/2)./(R+delta_ios)+1))-C(2)).^2);
tf = @(R, lhs, C1, C2, ctheta) (lhs*((R+ctheta/3)./(R+ctheta/2))*((R+ctheta*C1)./(R+ctheta/2)))/((ctheta.^4)*((R+ctheta/2)/(R+ctheta)+1))-C2;

[A, afval] = fminunc(var_f, 1);
[C, fval] = fminunc(ef, [0.7, 0.1]);

C1 = C(1)*ones(size(R)); C2 = C(2)*ones(size(R));

ctheta = arrayfun(@(rR, llhs, cC1, cC2) fzero(@(tT) tf(rR, llhs, cC1, cC2, tT), 0.05), R, lhs, C1, C2);

figure
plot(U, k.*((2*R+2*ctheta/3)./((R+ctheta/2).*(ctheta.^2)))./(((R+ctheta/2)./(R+ctheta))+1), '*');

xishu2 = 2*(((R+delta_ios/3)./(R+delta_ios/2)).*((R+delta_ios*A)./(R+delta_ios/2)))./((R+delta_ios/2)./(R+delta_ios)+1);
figure
plot(delta_ios, power(xishu2.*lhs, 1/4), '*')